### ISSUE TITLE
Getting Deployment is not a registered command

### ISSUE THREAD

**Issue by rakeenaa2** [citizen-of-planet-earth/cf-cli-action#7]
This is the config I have in the yaml

```
      - name: CF CLI Deploy
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: ${{ vars.SAP_CLOUD_HOST }}
          cf_username: ${{ vars.SAP_CLOUD_USER }}
          cf_password: ${{ secrets.SAP_CLOUD_PASSWORD }}
          cf_org: OGE
          cf_space: ${{ vars.SAP_CLOUD_SUB_ACCOUNT }}
          command: deploy ./**.mtar -f

```

This is the error I am getting:

`'deploy' is not a registered command. See 'cf help -a'`
